<div id="terms" class="overlay hidden bottom">
<div class="close"></div>
<h2>Terms of Use</h2>
<div class="overlay-wrapper">
<p>Hanson & Wen LLC and its affiliates ("Hanson & Wen" or "we") provides its content on this Web site (the "Site") subject to the following terms and conditions (the "Terms"). We may periodically change the Terms, so please check back from time to time. By accessing and using this Site, you agree to these Terms. For an explanation of Hanson & Wen's practices and policies related to the collection, use, and storage of our users' information, please read our Privacy Policy.</p>
 
​<strong class="upper">1. COPYRIGHTS</strong>
<p>All content and functionality on the Site, including text, graphics, logos, icons, and images and the selection and arrangement thereof, is the exclusive property of Hanson & Wen or its licensors and is protected by U.S. and international copyright laws. All rights not expressly granted are reserved.</p>
​
<strong class="upper">2. TRADEMARKS</strong>
<p>The trademarks, service marks, designs, and logos (collectively, the "Trademarks") displayed on the Site are the registered and unregistered Trademarks of Hanson & Wen and its licensors. You agree that you will not refer to or attribute any information to Hanson & Wen or its licensors in any public medium (e.g., press release, Web sites) for advertising or promotion purposes, or for the purpose of informing or influencing any third party and that you will not use or reproduce any Trademark of, or imply any endorsement by or relationship with, Hanson & Wen or its licensors.</p>
 
​<strong class="upper">3. USE OF SITE CONTENT</strong>
<p>Hanson & Wen hereby grants you a non-exclusive, non-transferable license for the term hereof to access and download, display, and print one copy of the content and functionality displayed on the Site (the "Site Content") on any single computer solely for your internal, business use, provided that you do not modify the Site Content in any way and that you retain all copyright and other proprietary notices displayed on the Site Content. You may not otherwise reproduce, modify, distribute, transmit, post, or disclose the Site Content without Hanson & Wen's prior written consent.</p>
 
​<strong class="upper">4. NOTICE OF INFRINGEMENT</strong>
<p>Hanson & Wen prohibits the posting of any content that infringes or violates the copyright rights and/or other intellectual property rights (including rights of privacy and publicity) of any person or entity. If you believe that your intellectual property right (or such a right that you are responsible for enforcing) is infringed by any content on the Site, please write to Hanson & Wen at the address shown below, giving a written statement that contains: (a) identification of the copyrighted work and/or intellectual property right claimed to have been infringed; (b) identification of the allegedly infringing material on the Site that is requested to be removed; (c) your name, address, and daytime telephone number, and an e-mail address if available; (d) a statement that you have a good faith belief that the use of the copyrighted work and/or exercise of the intellectual property right is not authorized by the owner, its agent, or the law; (e) a statement that the information in the notification is accurate, and, under penalty of perjury, that the signatory is authorized to act on behalf of the owner of the right that is allegedly infringed; and (f) the signature of the intellectual property right owner or someone authorized on the owner's behalf to assert infringement of the right. Hanson & Wen will remove any posted content that infringes the copyright or other intellectual property right of any person under U.S. law upon receipt of such a statement (or any statement in conformance with 17 U.S.C. 512(c)(3)). Hanson & Wen's contact for submission of notices under this Section 4 is: Hanson & Wen LLC, 7083 Hollywood Blvd, Los Angeles, CA 90028.</p>
 
​<strong class="upper">5. DISCLAIMERS</strong>
<p>THE CONTENT AND FUNCTIONALITY ON THE SITE IS PROVIDED WITH THE UNDERSTANDING THAT HANSON & WEN IS NOT HEREIN ENGAGED IN RENDERING PROFESSIONAL ADVICE AND SERVICES TO YOU. ALL CONTENT AND FUNCTIONALITY ON THE SITE IS PROVIDED "AS IS," WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING , WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. HANSON & WEN AND ITS THIRD-PARTY CONTENT PROVIDERS MAKE NO WARRANTIES, EXPRESS OR IMPLIED, AS TO THE OWNERSHIP, ACCURACY, OR ADEQUACY OF THE SITE CONTENT. HANSON & WEN SHALL HAVE NO LIABILITY OR RESPONSIBILITY FOR ANY INFORMATION PUBLISHED ON LINKED WEB SITES, CONTAINED IN ANY CONTENT PUBLISHED ON THE SITE, OR PROVIDED BY THIRD PARTIES. NEITHER HANSON & WEN NOR ITS THIRD-PARTY CONTENT PROVIDERS SHALL BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES OR FOR LOST REVENUES OR PROFITS, WHETHER OR NOT ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES AND REGARDLESS OF THE THEORY OF LIABILITY.</p>
 
​<strong class="upper">6. THIRD-PARTY WEB SITES</strong>
<p>We may provide links to third-party Web sites, and some of the content appearing to be on this Site is in fact supplied by third parties, for example, in instances of framing of third-party Web sites or incorporation through framesets of content supplied by third-party servers. Hanson & Wen has no responsibility for these third-party Web sites, which are governed by the Terms of Use and privacy policies, if any, of the applicable third-party content providers.</p>
 
​<strong class="upper">7. GOVERNING LAW; JURISDICTION</strong>
<p>These Terms are governed by the laws of the California without reference to the principles of conflicts of laws thereof. Any dispute arising from these Terms shall be resolved exclusively in the state and federal courts of California.</p>
</div>
</div>